export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

export const FETCH_COURSE_REQUEST = "FETCH_COURSE_REQUEST";
export const FETCH_COURSE_SUCCESS = "FETCH_COURSE_SUCCESS";
export const FETCH_COURSE_FAILURE = "FETCH_COURSE_FAILURE";

export const ADD_COURSE_ELEMENT = "ADD_COURSE_ELEMENT";
export const DELETE_COURSE_ELEMENT = "DELETE_COURSE_ELEMENT";
export const CHANGE_COURSE_ELEMENT = "CHANGE_COURSE_ELEMENT";

export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILURE = "ADD_COURSE_FAILURE";

export const DELETE_COURSE_REQUEST = "DELETE_COURSE_REQUEST";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_COURSE_FAILURE = "DELETE_COURSE_FAILURE";

export const CHANGE_COURSE_REQUEST = "CHANGE_COURSE_REQUEST";
export const CHANGE_COURSE_SUCCESS = "CHANGE_COURSE_SUCCESS";
export const CHANGE_COURSE_FAILURE = "CHANGE_COURSE_FAILURE";



