export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

export const ADD_COURSE_ELEMENT = "ADD_COURSE_ELEMENT";
export const DELETE_COURSE_ELEMENT = "DELETE_COURSE_ELEMENT";
export const CHANGE_COURSE_ELEMENT = "CHANGE_COURSE_ELEMENT";

