export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";


export const GETALL_ELEMENT_REQUEST = "GETALL_ELEMENT_REQUEST";
export const GETALL_ELEMENT_FAILURE = "GETALL_ELEMENT_FAILURE";
export const GETALL_COURSE_SUCCESS = "GETALL_COURSE_SUCCESS";
export const GETALL_BADGE_SUCCESS = "GETALL_BADGE_SUCCESS";
export const GETALL_LESSON_SUCCESS = "GETALL_LESSON_SUCCESS";


export const ADD_ELEMENT_REQUEST = "ADD_ELEMENT_REQUEST";
export const ADD_ELEMENT_FAILURE = "ADD_ELEMENT_FAILURE";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_BADGE_SUCCESS = "ADD_BADGE_SUCCESS";
export const ADD_LESSON_SUCCESS = "ADD_LESSON_SUCCESS";


export const DELETE_ELEMENT_REQUEST = "DELETE_ELEMENT_REQUEST";
export const DELETE_ELEMENT_FAILURE = "DELETE_ELEMENT_FAILURE";
export const DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
export const DELETE_BADGE_SUCCESS = "DELETE_BADGE_SUCCESS";
export const DELETE_LESSON_SUCCESS = "DELETE_LESSON_SUCCESS";


export const CHANGE_ELEMENT_REQUEST = "CHANGE_ELEMENT_REQUEST";
export const CHANGE_ELEMENT_FAILURE = "CHANGE_ELEMENT_FAILURE";
export const CHANGE_COURSE_SUCCESS = "CHANGE_COURSE_SUCCESS";
export const CHANGE_BADGE_SUCCESS = "CHANGE_BADGE_SUCCESS";
export const CHANGE_LESSON_SUCCESS = "CHANGE_LESSON_SUCCESS";

export const GET_LESSON_REQUEST = "GET_LESSON_REQUEST";
export const GET_LESSON_SUCCESS = "GET_LESSON_SUCCESS";
export const GET_LESSON_FAILURE = "GET_LESSON_FAILURE";


export const ADD_PAGE_REQUEST = "ADD_PAGE_REQUEST"
export const ADD_PAGE_SUCCESS = "ADD_PAGE_SUCCESS"
export const ADD_PAGE_FAILURE = "ADD_PAGE_FAILURE"

export const DELETE_PAGE_REQUEST = "DELETE_PAGE_REQUEST"
export const DELETE_PAGE_SUCCESS = "DELETE_PAGE_SUCCESS"
export const DELETE_PAGE_FAILURE = "DELETE_PAGE_FAILURE"

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS"
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE"

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST"
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS"
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE"

export const ADD_TEST_TASK = "ADD_TEST_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const CHANGE_TEST_TASK = "CHANGE_TEST_TASK"



